[server]
headless = true
enableCORS = false
enableXsrfProtection = false
enableWebsocketCompression = false
runOnSave = false
port = 8000
address = "0.0.0.0"

[browser]
serverAddress = "0.0.0.0"
serverPort = 8000
